In [1]:
import numpy as np 
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

In [4]:
type(list_)

list

In [5]:
type(array_list)

numpy.ndarray

In [6]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [16]:
# ques 1 
##ans - list refers to a collection of various elements in a sequence , in which every element is basically an object
 # and in  other hand , an  array list creates an array of the object that can easily reduce or increase in size as and when required
import numpy as np 
list1 =['31','8','7','2005']
array_list=np.array([[1,2,3,4],[2,3,4,5]])

In [17]:
array_list

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [18]:
list1

['31', '8', '7', '2005']

In [22]:
# ques 2
#ans- 
type(list1) 


list

In [23]:
type(array_list)

numpy.ndarray

In [24]:
array_list=np.array(object=list_,dtype=int)

In [25]:
array_list

array([1, 2, 3, 4, 5])

In [26]:
#ques3
#ans- yes , there is a difference in datatype ,both the variable list_ and arra_list 
type(list_)

list

In [28]:
type(array_list)

numpy.ndarray

In [29]:
# code for ques 4, 5,6
num_list=[[1,2,3],[4,5,6]]
num_array=np.array(object = num_list)

In [31]:
# Ques 4 - ans -->
np.shape(num_list)

(2, 3)

In [32]:
np.shape(num_array)

(2, 3)

In [36]:
np.size(num_array)

6

In [39]:
#Ques 5
#ans-
arr3=np.zeros((3,3))

In [40]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.size(arr3)

9

In [42]:
np.shape(arr3)

(3, 3)

In [44]:
#Ques 6 
# Ans -
arr4 = np.eye(5,5)

In [45]:
arr4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])